# Generated by Django 3.1.1 on 2021-06-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='txtfile',
            field=models.FileField(null=True, upload_to='Qgenerators/'),
        ),
    ]
